apiVersion: v2
name: sentry
description: A Helm chart for Kubernetes
type: application
version: 13.1.0
appVersion: 21.8.0
dependencies:
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 15.3.2
    condition: redis.enabled
  - name: kafka
    repository: https://charts.bitnami.com/bitnami
    version: ~14.2.1
    condition: kafka.enabled
  - name: clickhouse
    repository: https://gitlab.motius.de/api/v4/projects/2194/packages/helm/stable
    version: 3.1.2
    condition: clickhouse.enabled
  - name: rabbitmq
    repository: https://charts.bitnami.com/bitnami
    version: 8.9.1
    alias: rabbitmq
    condition: rabbitmq.enabled
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 10.2.4
    condition: postgresql.enabled
  - name: nginx
    repository: https://charts.bitnami.com/bitnami
    version: 9.3.3
    condition: nginx.enabled
